language: python
python:
#  - "3.4"
#  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO=1.4.16
  - DJANGO=1.5.11
  - DJANGO=1.6.8
  - DJANGO=1.7.1
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.1
#    - python: "3.3"
#      env: DJANGO=1.4.16
#    - python: "3.4"
#      env: DJANGO=1.4.16
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls mock
script:
  - coverage run --source=simple_elasticsearch setup.py test
after_success:
  - coveralls

